feature(common): the whole process for placing an order is added [WEB…
juan865010/ecommerce-frontend-magneta pull request #3
Opened 2023-07-06 21:33 UTC by juan865010

the whole process for placing an order is added

2023-07-08 04:51 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/f58e1d5b-3736-469d-bea4-66236e2e64d9)

![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/8d77a222-f20c-40ce-a9e2-b5007d35ebf5)

![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/2360db19-cee2-4c6d-8aec-70c17904573a)

![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/55a4c9c7-badf-4dc9-9c35-a278b4ff952e)

It is not according to Figma. correct the following: (size of the texts, space between the inputs name and surname, add checkbox lorem, modify the size of the checkbox shipping delivery payment)

2023-07-10 12:24 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/a430d39b-7d63-4d14-abbe-37acd1f503f3)
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/e0202fff-7a3a-4bf0-aa14-b6b1ec4d0e58)

It is according to Figma. continue with the same interest.👍

2023-07-13 22:23 UTC, Ditmar requested changes
nice pr great work

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/confirmOrder/ConfirmOrder.jsx
> +import useStyles from "./confirmOrder.styles";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/confirmOrder/ConfirmOrder.jsx
> +import OrderSend from "../infoFacSend/orderSend/OrderSend";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/confirmOrder/ConfirmOrder.jsx
> +import Confirm from "./confirm/Confirm";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/confirmOrder/confirm/Confirm.jsx
> +import useStyles from "./confirm.styles";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/infoFacSend/InfoFacSend.jsx
> +import useStyles from "./InfoFacSend.styles";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/infoFacSend/InfoFacSend.jsx
> +import OrderSend from "./orderSend/OrderSend";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/infoFacSend/InfoFacSend.jsx
> +import CheckForm from "./checkForm/CheckForm";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/infoFacSend/InfoFacSend.jsx
> +import BreadCrumb from "./breadCrumb/BreadCrumb";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/infoFacSend/breadCrumb/BreadCrumb.jsx
> +import Breadcrumbs from "@mui/material/Breadcrumbs";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/infoFacSend/breadCrumb/BreadCrumb.jsx
> +import Link from "@mui/material/Link";
please use single quotes

2023-07-13 22:23 UTC, Ditmar commented on src/ui/components/infoFacSend/breadCrumb/BreadCrumb.jsx
> +import HorizontalRuleIcon from "@mui/icons-material/HorizontalRule";
please use single quotes

2023-07-14 14:58 UTC, merged