feature(common):add order confirmation
juan865010/ecommerce-frontend-magneta pull request #4
Opened 2023-07-07 00:47 UTC by MailyCristi

adding the confirmation page

2023-07-08 04:38 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/f2dbca30-9aad-44dc-9f76-89028e655b52)

It is not according to Figma. correct the following: (color of the components, color and size of the texts)

2023-07-12 10:49 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/9936986c-c81c-40d9-93d1-8ff1a11bb544)

It is according to Figma. Continue with the same interest.👍

2023-07-14 01:29 UTC, Ditmar requested changes
read the comments below

2023-07-14 01:29 UTC, Ditmar commented on src/ui/components/ConfirmacionDeCompra/ConfirmacionDeCompra.jsx
> +                        <svg className={classes.icon} width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
use the icon component

2023-07-14 01:29 UTC, Ditmar commented on src/ui/components/ConfirmacionDeCompra/ConfirmacionDeCompra.jsx
> +const ConfirmacionDeCompra = () => {
use english

2023-07-14 13:29 UTC, Ditmar approved these changes
approved

2023-07-14 14:09 UTC, merged