adding the files of the ticket  16
juan865010/ecommerce-frontend-magneta pull request #5
Opened 2023-07-07 04:03 UTC by AlexDanielGutierrezCardenas

files [WEBSITE-16]

2023-07-08 04:29 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/d69d8eb7-8121-4b1f-8a29-478c92749a0d)

It is not according to Figma. fix the following: (check the size of the components, positioning of layers and the color of the texts)

2023-07-11 01:55 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/b0b1fa60-5339-455e-9aee-97727058ab76)
 
It is according to the figma. Continue with the same interest.👍

2023-07-13 23:07 UTC, Ditmar requested changes
many conflicts  in the pr

2023-07-13 23:07 UTC, Ditmar commented on src/ui/components/HistorialPedidos/FiltrarPedidos.jsx
> -=======
remove you have conflicts in the pr

2023-07-13 23:07 UTC, Ditmar commented on src/ui/components/HistorialPedidos/FiltrarPedidos.jsx
> ->>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
more conflicts

2023-07-13 23:07 UTC, Ditmar commented on src/ui/components/HistorialPedidos/FiltrarPedidos.jsx
> ->>>>>>> 4f158bd19a70584a1352ff6855ae646539b582e0
more conflicts

2023-07-13 23:09 UTC, Ditmar approved these changes
nice work approved

2023-07-14 13:23 UTC, Ditmar approved these changes
approved

2023-07-14 13:23 UTC, merged