feature(common): adding the file of list opinions in the files [WEBSI…
juan865010/ecommerce-frontend-magneta pull request #7
Opened 2023-07-07 21:39 UTC by samquis

##summary
adding the file of list opinions

2023-07-08 04:18 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/6f23b3c0-102f-4873-88a3-07eeac7c08eb)

It is not according to Figma. fix the following: (check layer positioning)

2023-07-13 14:04 UTC, olmedo90 commented
![image](https://github.com/juan865010/ecommerce-frontend-magneta/assets/77794323/528bf5df-4dbd-45c6-b715-ae2638c28b52)

It is according to Figma. Continue with the same interest.👍

2023-07-14 01:24 UTC, Ditmar requested changes
please review the comments

2023-07-14 01:24 UTC, Ditmar commented on src/App.js
> +import Opinions from "./ui/components/opinions/Listaopinion"
use simple quotes

2023-07-14 01:24 UTC, Ditmar commented on src/ui/components/opinions/Listaopinion_style.js
> +        backgroundColor:'#FFFFFF',
the color must have  come from the main Theme file something like this theme.palette.color

2023-07-14 01:24 UTC, Ditmar commented on src/ui/components/opinions/Listaopinion.jsx
> +  const classes = useStyles();
don´t use Spanish use english

2023-07-14 14:09 UTC, Ditmar approved these changes
approved

2023-07-14 15:24 UTC, merged